apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-21T11:39:40Z"
  name: carts-canary
  resourceVersion: "932557"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: 9aa9fab8-0c53-11ea-b7f3-42010a8401a9
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
